---

name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-master:
    run: echo "I am master"
    if: ${{ github.ref == 'refs/heads/master' }}

  run-no-master:
    run: echo "I am no master"
    if: ${{ github.ref != 'refs/heads/master' }}
