---

name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-master:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am master"
        if: ${{ github.ref == 'refs/heads/master' }}

  run-no-master:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am no master"
        if: ${{ github.ref != 'refs/heads/master' }}
